global:
  scrape_interval: 5s
  # metrics_path: v1/user-service/metrics
scrape_configs:
  - job_name: 'mongocrud'
    metrics_path: /v1/user-service/metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
