apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090
    access: direct
    basicAuth: false
    isDefault: true
    editable: true
